# Generated by Django 4.2.7 on 2024-02-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="short_description",
            field=models.CharField(
                default=None,
                max_length=250,
                null=True,
                verbose_name="description courte",
            ),
        ),
    ]
