# Generated by Django 4.2.7 on 2023-11-25 15:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_menu_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proof_of_id',
            field=models.FileField(default='dsds', upload_to='proof_of_id/', verbose_name="preuve d'identité"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='dsd', max_length=128, region=None, unique=True, verbose_name='numéro de téléphone mobile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='mot de passe'),
        ),
    ]
