# Generated by Django 4.2.7 on 2023-11-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_proof_of_id_alter_user_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
