# Generated by Django 4.2.7 on 2024-09-03 14:02

import autoslug.fields
import core.models.fields.json_field
import core.models.fields.model_select_field
from decimal import Decimal
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import djmoney.models.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="marque")),
                ("model", models.CharField(max_length=100, verbose_name="modèle")),
                ("color", models.CharField(max_length=100, verbose_name="couleur")),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="numéro d'identification du véhicule",
                    ),
                ),
                (
                    "licence",
                    models.CharField(
                        max_length=100, verbose_name="plaque d'immatriculation"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "driver",
                    core.models.fields.model_select_field.ModelSelect(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_driver",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="chauffeur",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "véhicule",
                "verbose_name_plural": "véhicules",
            },
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("accepted", "accepted"),
                            ("started", "started"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                            ("failed", "failed"),
                            ("ended", "ended"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "pick_up_address",
                    models.CharField(
                        max_length=255, verbose_name="nom du lieu de ramassage"
                    ),
                ),
                (
                    "pick_up_location",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=4326, verbose_name="lieu de ramassage"
                    ),
                ),
                (
                    "vehicle",
                    models.CharField(
                        choices=[
                            ("voiture", "voiture"),
                            ("mini-bus", "mini-bus"),
                            ("jeep 4x4", "jeep 4x4"),
                        ],
                        default="voiture",
                        max_length=100,
                        verbose_name="vehicule",
                    ),
                ),
                (
                    "duration_in_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="duration"),
                ),
                (
                    "cost_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("CDF", "CDF"), ("USD", "USD")],
                        default="CDF",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "cost",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "paid_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("CDF", "CDF"), ("USD", "USD")],
                        default="CDF",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "paid",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(default=0, verbose_name="rating"),
                ),
                (
                    "review",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="review"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "driver",
                    core.models.fields.model_select_field.ModelSelect(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_driver",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="chauffeur",
                    ),
                ),
                (
                    "passenger",
                    core.models.fields.model_select_field.ModelSelect(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_passenger",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="passenger",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "ordering": ("-updated_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="url")),
                ("title", models.CharField(max_length=255, verbose_name="titre")),
                (
                    "content",
                    tinymce.models.HTMLField(null=True, verbose_name="contenu"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "app page",
                "verbose_name_plural": "app pages",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                (
                    "pick_up_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        editable=False,
                        null=True,
                        srid=4326,
                        verbose_name="lieu de ramassage",
                    ),
                ),
                (
                    "pick_up_address",
                    models.CharField(
                        max_length=255, verbose_name="nom du lieu de ramassage"
                    ),
                ),
                (
                    "vehicle",
                    models.CharField(
                        choices=[
                            ("voiture", "voiture"),
                            ("mini-bus", "mini-bus"),
                            ("jeep 4x4", "jeep 4x4"),
                        ],
                        default="voiture",
                        max_length=100,
                        verbose_name="vehicule",
                    ),
                ),
                (
                    "duration_in_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="duree en minute"
                    ),
                ),
                (
                    "price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("CDF", "CDF"), ("USD", "USD")],
                        default="CDF",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "price",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=14,
                        verbose_name="prix",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "pro-forma",
                "verbose_name_plural": "pro-formas",
            },
        ),
    ]
