# Generated by Django 4.2.7 on 2023-12-01 08:28

import autoslug.fields
import core.models.fields.json_field
import core.models.fields.model_select_field
import core.models.fields.model_select_to_multiple_field
import core.models.fields.model_select_to_signle_field
import core.models.fields.time_field
import core.utils
from decimal import Decimal
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import djmoney.models.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('brand', models.CharField(max_length=100, verbose_name='marque')),
                ('model', models.CharField(max_length=100, verbose_name='modèle')),
                ('color', models.CharField(max_length=100, verbose_name='couleur')),
                ('vin', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name="numéro d'identification du véhicule")),
                ('license_plate', models.CharField(max_length=100, verbose_name="plaque d'immatriculation")),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'véhicule',
                'verbose_name_plural': 'véhicules',
            },
        ),
        migrations.CreateModel(
            name='ScheduledRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('drop_off', models.CharField(max_length=100, verbose_name='drop off')),
                ('pick_up', models.CharField(max_length=100, verbose_name='pick up')),
                ('pick_up_time', core.models.fields.time_field.TimeField(verbose_name='heure de prise en charge')),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='USD', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14)),
                ('paid_currency', djmoney.models.fields.CurrencyField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='USD', editable=False, max_length=3)),
                ('paid', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED')], default='CREATED', max_length=10, verbose_name='état')),
                ('client', core.models.fields.model_select_field.ModelSelect(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_driver', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('driver', core.models.fields.model_select_field.ModelSelect(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_client', to=settings.AUTH_USER_MODEL, verbose_name='chauffeur')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'course programmée',
                'verbose_name_plural': 'courses programmée',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('started', 'started'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('failed', 'failed')], default='pending', max_length=20, verbose_name='état')),
                ('pick_up_address', models.CharField(max_length=255, verbose_name='nom du lieu de ramassage')),
                ('pick_up_location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='lieu de ramassage')),
                ('duration_in_minutes', models.PositiveIntegerField(default=0, verbose_name='duration')),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('paid_currency', djmoney.models.fields.CurrencyField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', editable=False, max_length=3)),
                ('paid', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('driver', core.models.fields.model_select_field.ModelSelect(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_driver', to=settings.AUTH_USER_MODEL, verbose_name='chauffeur')),
                ('passenger', core.models.fields.model_select_field.ModelSelect(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_passenger', to=settings.AUTH_USER_MODEL, verbose_name='passenger')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('title', models.CharField(max_length=100, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('attach', models.ImageField(blank=True, default=None, null=True, upload_to=core.utils.upload_directory_file, verbose_name='joindre')),
                ('type_of_user', models.CharField(blank=True, choices=[('-', ''), ('client', 'client'), ('driver', 'chauffeur')], default=None, max_length=10, null=True, verbose_name="type d'utilisateur")),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
                ('users', core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(to=settings.AUTH_USER_MODEL, verbose_name='utilisateurs')),
            ],
            options={
                'verbose_name': 'notification push',
                'verbose_name_plural': 'notifications push',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('content', tinymce.models.HTMLField(null=True, verbose_name='contenu')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('pick_up_location', django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=4326, verbose_name='lieu de ramassage')),
                ('pick_up_address', models.CharField(max_length=255, verbose_name='nom du lieu de ramassage')),
                ('duration_in_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='duree en minute')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14, verbose_name='prix')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'pro-forma',
                'verbose_name_plural': 'pro-formas',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('is_active', models.BooleanField(default=False, verbose_name='est actif')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
                ('user', core.models.fields.model_select_to_signle_field.ModelSelect2Single(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicule', core.models.fields.model_select_to_signle_field.ModelSelect2Single(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.vehicule')),
            ],
            options={
                'verbose_name': 'chauffeur',
                'verbose_name_plural': 'chauffeurs',
                'unique_together': {('vehicule', 'user')},
            },
        ),
    ]
