# Generated by Django 4.2.7 on 2024-09-03 16:23

import core.models.fields.choice_field
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="last_know_location",
            field=django.contrib.gis.db.models.fields.PointField(
                null=True, srid=4326, verbose_name="dernier lieu connu"
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=core.models.fields.choice_field.ChoiceField(
                choices=[
                    ("pending", "pending"),
                    ("accepted", "accepted"),
                    ("started", "started"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                    ("failed", "failed"),
                    ("ended", "ended"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
