# Generated by Django 4.2.7 on 2023-12-01 08:36

import core.models.fields.model_select_field
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_remove_ride_passenger_ride_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='client',
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger',
            field=core.models.fields.model_select_field.ModelSelect(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_passenger', to=settings.AUTH_USER_MODEL, verbose_name='passenger'),
            preserve_default=False,
        ),
    ]
