# Generated by Django 4.2.7 on 2023-11-10 17:57

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_scheduledride_pushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='attach',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=core.utils.upload_directory_file, verbose_name='joindre'),
        ),
    ]
