# Generated by Django 4.2.7 on 2023-12-01 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0004_remove_ride_client_ride_passenger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicule',
            new_name='Vehicle',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
