# Generated by Django 4.2.7 on 2023-12-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_vehicule_vehicle_delete_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='license_plate',
            new_name='licence',
        ),
    ]
