# Generated by Django 4.2.7 on 2023-11-25 15:57

import core.models.fields.model_select_field
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0005_remove_ride_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='client',
            field=core.models.fields.model_select_field.ModelSelect(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_client', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=core.models.fields.model_select_field.ModelSelect(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_driver', to=settings.AUTH_USER_MODEL, verbose_name='chauffeur'),
        ),
    ]
