# Generated by Django 4.2.7 on 2023-12-01 10:01

import core.models.fields.model_select_field
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0006_rename_license_plate_vehicle_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=core.models.fields.model_select_field.ModelSelect(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_driver', to=settings.AUTH_USER_MODEL, verbose_name='chauffeur'),
            preserve_default=False,
        ),
    ]
