# Generated by Django 4.2.7 on 2023-11-26 11:06

import core.models.fields.json_field
from decimal import Decimal
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0006_alter_ride_client_alter_ride_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='ride',
            name='paid_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('started', 'started'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('failed', 'failed')], default='pending', max_length=20, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='scheduledride',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='scheduledride',
            name='paid_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='USD', editable=False, max_length=3),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('metadata', core.models.fields.json_field.JSONField(blank=True, default=dict, verbose_name='meta')),
                ('pick_up_location', django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=4326, verbose_name='lieu de ramassage')),
                ('pick_up_location_name', models.CharField(max_length=255, verbose_name='nom du lieu de ramassage')),
                ('duration_in_minutes', models.IntegerField(blank=True, null=True, verbose_name='duree en minute')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14, verbose_name='prix')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'pro-forma',
                'verbose_name_plural': 'pro-formas',
            },
        ),
    ]
