# Generated by Django 4.2.7 on 2023-11-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_ride_cost_currency_alter_ride_paid_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='duration_in_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='duree en minute'),
        ),
    ]
