# Generated by Django 4.2.7 on 2023-12-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_vehicle_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='ride',
            name='review',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='review'),
        ),
    ]
