# Generated by Django 4.2.7 on 2023-12-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_ride_rating_ride_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
