# Generated by Django 4.2.7 on 2023-12-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('started', 'started'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('ended', 'ended')], default='pending', max_length=20, verbose_name='état'),
        ),
    ]
