# Generated by Django 4.2.7 on 2024-02-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0010_alter_ride_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledride",
            name="client",
        ),
        migrations.RemoveField(
            model_name="scheduledride",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="scheduledride",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="scheduledride",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="PushNotification",
        ),
        migrations.DeleteModel(
            name="ScheduledRide",
        ),
    ]
