# Generated by Django 4.2.7 on 2024-02-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0011_remove_scheduledride_client_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"verbose_name": "app page", "verbose_name_plural": "app pages"},
        ),
        migrations.AddField(
            model_name="invoice",
            name="vehicle",
            field=models.CharField(
                choices=[
                    ("voiture", "voiture"),
                    ("mini-bus", "mini-bus"),
                    ("jeep 4x4", "jeep 4x4"),
                ],
                default="voiture",
                max_length=100,
                verbose_name="vehicule",
            ),
        ),
    ]
